@LowCostFlights.Server_HostAddress = http://localhost:5132

GET {{LowCostFlights.Server_HostAddress}}/api/flightoffers/get
Accept: application/json
###

GET {{LowCostFlights.Server_HostAddress}}/api/
###